{
  description = "Rackctl — Linux control tools for audio hardware (Tascam US-16x08 mixer, BOSS GX-700) — CLI + GUI";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs =
    { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachDefaultSystem (
      system:
      let
        pkgs = nixpkgs.legacyPackages.${system};
        inherit (pkgs) lib;

        # One source of truth for the version: the workspace manifest, the same
        # field `bump-version` stamps. No need to touch this file at release time.
        version = (builtins.fromTOML (builtins.readFile ./Cargo.toml)).workspace.package.version;

        # Libraries eframe/winit/glow need. They are needed at build time (the
        # `-sys` crates link or probe them) and the GUI also dlopens several at
        # run time. The set mirrors the CI's apt packages:
        #   libasound2-dev   -> alsa-lib
        #   libgl1-mesa-dev  -> libGL
        #   libxkbcommon-dev -> libxkbcommon
        #   libwayland-dev   -> wayland
        #   libxcb*-dev      -> xorg.libxcb
        guiLibs = with pkgs; [
          libGL
          libxkbcommon
          wayland
          xorg.libxcb
          xorg.libX11
          xorg.libXcursor
          xorg.libXi
          xorg.libXrandr
        ];

        # The whole suite in one derivation: every device's CLI + GUI built from
        # the workspace, with each CLI's completions, both desktop entries, and the
        # GUIs wrapped for their dlopen'd runtime libraries.
        rackctl = pkgs.rustPlatform.buildRustPackage {
          pname = "rackctl";
          inherit version;
          src = self;

          # Build against the committed lockfile — no network, reproducible.
          cargoLock.lockFile = ./Cargo.lock;

          nativeBuildInputs = [
            pkgs.pkg-config
            pkgs.makeWrapper
            pkgs.installShellFiles
          ];
          buildInputs = [ pkgs.alsa-lib ] ++ guiLibs;

          postInstall = ''
            # Shell completions, generated by each CLI itself (no card needed —
            # `completions` does not open a device).
            for cli in rackctl-us16x08 rackctl-gx700 rackctl-eleven; do
              installShellCompletion --cmd "$cli" \
                --bash <($out/bin/"$cli" completions bash) \
                --fish <($out/bin/"$cli" completions fish) \
                --zsh  <($out/bin/"$cli" completions zsh)
            done

            # Desktop entries for the GUIs.
            install -Dm644 -t $out/share/applications packaging/*.desktop

            for gui in rackctl-us16x08-gui rackctl-gx700-gui rackctl-eleven-gui; do
              # App icon (referenced by the .desktop Icon= key) into the hicolor theme.
              install -Dm644 "packaging/$gui.svg" \
                "$out/share/icons/hicolor/scalable/apps/$gui.svg"

              # winit/glow load Wayland, GL and xkbcommon with dlopen at run time,
              # which does not consult the binary's RUNPATH — so put them on each
              # GUI's library path. The CLIs only need libasound, found via RUNPATH.
              wrapProgram $out/bin/"$gui" \
                --prefix LD_LIBRARY_PATH : ${lib.makeLibraryPath guiLibs}
            done
          '';

          meta = {
            description = "Rackctl — Linux control tools for the Tascam US-16x08 mixer, BOSS GX-700 and Avid Eleven Rack (CLI + GUI)";
            homepage = "https://github.com/malo-rte/rackctl";
            license = lib.licenses.mit;
            platforms = lib.platforms.linux;
            mainProgram = "rackctl-us16x08-gui";
          };
        };

        # One app per binary; bare `nix run` is the US-16x08 GUI.
        mkApp = name: {
          type = "app";
          program = "${rackctl}/bin/${name}";
        };
      in
      {
        packages = {
          default = rackctl;
          rackctl = rackctl;
        };

        # `nix run .#rackctl-gx700` (CLI) / `.#rackctl-gx700-gui` (GUI), and the
        # US-16x08 equivalents; bare `nix run` is the US-16x08 GUI.
        apps = {
          default = self.apps.${system}.rackctl-us16x08-gui;
          rackctl-us16x08 = mkApp "rackctl-us16x08";
          rackctl-us16x08-gui = mkApp "rackctl-us16x08-gui";
          rackctl-gx700 = mkApp "rackctl-gx700";
          rackctl-gx700-gui = mkApp "rackctl-gx700-gui";
          rackctl-eleven = mkApp "rackctl-eleven";
          rackctl-eleven-gui = mkApp "rackctl-eleven-gui";
        };

        # `nix develop` — the build inputs plus the Rust toolchain and the gate's
        # tools. LD_LIBRARY_PATH lets a plain `cargo run -p <gui>` find the GUIs'
        # runtime libraries.
        devShells.default = pkgs.mkShell {
          inputsFrom = [ rackctl ];
          packages = with pkgs; [
            cargo
            rustc
            clippy
            rustfmt
            rust-analyzer
          ];
          LD_LIBRARY_PATH = lib.makeLibraryPath guiLibs;
        };
      }
    );
}
